export const calculators = [
  {
    id: 'bsa',
    name: 'BSA・BMI・PBW',
    description: '体表面積・BMI・予測体重を算出',
    icon: '📐',
    path: '/calculator/bsa',
    enabled: true,
  },
  {
    id: 'size',
    name: 'サイズ換算',
    description: 'mm / Fr / inch の換算、G(ゲージ)対応表',
    icon: '📏',
    path: '/calculator/size',
    enabled: true,
  },
  {
    id: 'egfr',
    name: 'eGFR / CCr',
    description: '腎機能評価（eGFR・クレアチニンクリアランス）',
    icon: '🔬',
    path: '/calculator/egfr',
    enabled: true,
  },
  {
    id: 'gamma',
    name: 'ガンマ計算機',
    description: '薬剤投与速度のγ計算・逆算',
    icon: '💊',
    path: '/calculator/gamma',
    enabled: true,
  },
  {
    id: 'cylinder',
    name: 'ボンベ残量',
    description: '医療用ガスボンベの残量・使用可能時間',
    icon: '🔋',
    path: '/calculator/cylinder',
    enabled: true,
  },
  {
    id: 'memos',
    name: 'マイノート',
    description: '計算結果や申し送りを記録するメモ帳',
    icon: '📝',
    path: '/memos',
    enabled: true,
  },
];
